#!/usr/bin/env python3
"""Minimal BDF -> LVGL bpp=1 .c converter.

Mirrors the structure of LVGL's stock 1bpp fonts (e.g. lv_font_unscii_8.c) so
the produced files plug into the same get_glyph_dsc_fmt_txt / get_bitmap_fmt_txt
pipeline.
"""
import re
import sys
from pathlib import Path


def parse_bdf(path: Path):
    """Return (font_props, [glyphs])."""
    text = path.read_text(errors="replace").splitlines()
    i = 0
    props = {}
    glyphs = []
    while i < len(text):
        line = text[i].rstrip()
        toks = line.split(None, 1)
        if not toks:
            i += 1
            continue
        kw = toks[0]

        if kw == "FONTBOUNDINGBOX":
            w, h, ox, oy = (int(x) for x in toks[1].split())
            props["fbbx"] = (w, h, ox, oy)
        elif kw == "FONT_ASCENT":
            props["ascent"] = int(toks[1])
        elif kw == "FONT_DESCENT":
            props["descent"] = int(toks[1])
        elif kw == "PIXEL_SIZE":
            props["pixel_size"] = int(toks[1])
        elif kw == "STARTCHAR":
            g = {"name": toks[1] if len(toks) > 1 else ""}
            i += 1
            while i < len(text) and not text[i].startswith("ENDCHAR"):
                line2 = text[i].rstrip()
                t2 = line2.split(None, 1)
                if not t2:
                    i += 1
                    continue
                k = t2[0]
                if k == "ENCODING":
                    g["enc"] = int(t2[1])
                elif k == "DWIDTH":
                    g["dwidth"] = int(t2[1].split()[0])
                elif k == "BBX":
                    bbw, bbh, ofx, ofy = (int(x) for x in t2[1].split())
                    g["bbx"] = (bbw, bbh, ofx, ofy)
                elif k == "BITMAP":
                    rows = []
                    i += 1
                    while i < len(text) and not text[i].startswith("ENDCHAR"):
                        rows.append(text[i].strip())
                        i += 1
                    g["rows"] = rows
                    break
                i += 1
            glyphs.append(g)
        i += 1
    return props, glyphs


def pack_glyph_bits(g):
    """Convert BDF byte-aligned rows -> LVGL bit-packed (MSB first, no row pad)."""
    bbw, bbh, _, _ = g.get("bbx", (0, 0, 0, 0))
    if bbw == 0 or bbh == 0:
        return b""
    bits = []
    for r in g["rows"][:bbh]:
        v = int(r, 16)
        row_bytes = (bbw + 7) // 8
        # Hex string represents `row_bytes` bytes left-justified in a wider word.
        # Number of hex digits = row_bytes * 2.
        hex_digits = row_bytes * 2
        # Re-read as fixed-width unsigned int
        v = int(r, 16) if r else 0
        # Bits from MSB of the row's leftmost byte, take bbw bits
        for b in range(bbw):
            byte_idx = b // 8
            bit_in_byte = 7 - (b % 8)
            byte_val = (v >> ((row_bytes - 1 - byte_idx) * 8)) & 0xFF
            bit = (byte_val >> bit_in_byte) & 1
            bits.append(bit)
    # Pack bits MSB-first into bytes
    out = bytearray()
    cur = 0
    cnt = 0
    for bit in bits:
        cur = (cur << 1) | bit
        cnt += 1
        if cnt == 8:
            out.append(cur)
            cur, cnt = 0, 0
    if cnt:
        out.append(cur << (8 - cnt))
    return bytes(out)


def emit(font_name: str, props: dict, glyphs: list, out_path: Path, pixel_size: int):
    # Sort by encoding, only ASCII printable 0x20-0x7E (95 glyphs).
    by_enc = {g["enc"]: g for g in glyphs if "enc" in g}
    glyphs_in = [by_enc.get(c) for c in range(0x20, 0x7F)]
    # If a glyph is missing, synthesize an empty one with width=fontwidth.
    fbbx = props.get("fbbx", (pixel_size, pixel_size, 0, 0))
    default_dwidth = max(fbbx[0], 1)
    for idx, g in enumerate(glyphs_in):
        if g is None:
            glyphs_in[idx] = {
                "enc": 0x20 + idx,
                "dwidth": default_dwidth,
                "bbx": (0, 0, 0, 0),
                "rows": [],
            }

    bitmaps = [pack_glyph_bits(g) for g in glyphs_in]
    bitmap_offsets = []
    off = 0
    for b in bitmaps:
        bitmap_offsets.append(off)
        off += len(b)

    ascent = props.get("ascent", fbbx[1] + fbbx[3])
    descent = props.get("descent", -fbbx[3] if fbbx[3] < 0 else 0)
    line_height = ascent + descent
    if line_height <= 0:
        line_height = pixel_size + 1

    macro = f"LV_FONT_{font_name.upper()}"
    decl_name = f"lv_font_{font_name}"

    lines = []
    lines.append('/* Auto-generated by tools/bdf2lvgl.py — bpp=1 */')
    lines.append('#ifdef LV_LVGL_H_INCLUDE_SIMPLE')
    lines.append('#include "lvgl.h"')
    lines.append('#else')
    lines.append('#include "../../lvgl.h"')
    lines.append('#endif')
    lines.append('')
    lines.append(f'#ifndef {macro}')
    lines.append(f'#define {macro} 1')
    lines.append('#endif')
    lines.append('')
    lines.append(f'#if {macro}')
    lines.append('')
    lines.append('static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {')
    for g, b in zip(glyphs_in, bitmaps):
        if not b:
            lines.append(f'    /* U+{g["enc"]:04X} */ 0x0,')
        else:
            hexs = ", ".join(f'0x{x:02x}' for x in b)
            lines.append(f'    /* U+{g["enc"]:04X} */ {hexs},')
    lines.append('};')
    lines.append('')
    lines.append('static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {')
    lines.append('    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},')
    for g, off_, b in zip(glyphs_in, bitmap_offsets, bitmaps):
        bbw, bbh, ofx, ofy = g.get("bbx", (0, 0, 0, 0))
        adv = g.get("dwidth", default_dwidth) * 16
        lines.append(
            f'    {{.bitmap_index = {off_}, .adv_w = {adv}, '
            f'.box_w = {bbw}, .box_h = {bbh}, .ofs_x = {ofx}, .ofs_y = {ofy}}},'
        )
    lines.append('};')
    lines.append('')
    lines.append('static const lv_font_fmt_txt_cmap_t cmaps[] = {')
    lines.append('    { .range_start = 32, .range_length = 95, .glyph_id_start = 1,')
    lines.append('      .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,')
    lines.append('      .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY }')
    lines.append('};')
    lines.append('')
    lines.append('#if LV_VERSION_CHECK(8, 0, 0)')
    lines.append('static lv_font_fmt_txt_glyph_cache_t cache;')
    lines.append('static const lv_font_fmt_txt_dsc_t font_dsc = {')
    lines.append('#else')
    lines.append('static lv_font_fmt_txt_dsc_t font_dsc = {')
    lines.append('#endif')
    lines.append('    .glyph_bitmap = glyph_bitmap,')
    lines.append('    .glyph_dsc = glyph_dsc,')
    lines.append('    .cmaps = cmaps,')
    lines.append('    .kern_dsc = NULL, .kern_scale = 0, .cmap_num = 1,')
    lines.append('    .bpp = 1, .kern_classes = 0, .bitmap_format = 0,')
    lines.append('#if LV_VERSION_CHECK(8, 0, 0)')
    lines.append('    .cache = &cache')
    lines.append('#endif')
    lines.append('};')
    lines.append('')
    lines.append('#if LV_VERSION_CHECK(8, 0, 0)')
    lines.append(f'const lv_font_t {decl_name} = {{')
    lines.append('#else')
    lines.append(f'lv_font_t {decl_name} = {{')
    lines.append('#endif')
    lines.append('    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,')
    lines.append('    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,')
    lines.append(f'    .line_height = {line_height},')
    lines.append(f'    .base_line = {descent},')
    lines.append('#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)')
    lines.append('    .subpx = LV_FONT_SUBPX_NONE,')
    lines.append('#endif')
    lines.append('#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8')
    lines.append('    .underline_position = 0,')
    lines.append('    .underline_thickness = 0,')
    lines.append('#endif')
    lines.append('    .dsc = &font_dsc')
    lines.append('};')
    lines.append('')
    lines.append(f'#endif /*#if {macro}*/')
    lines.append('')
    out_path.write_text("\n".join(lines))


def main():
    if len(sys.argv) != 4:
        print("usage: bdf2lvgl.py <input.bdf> <font_name> <output.c>")
        sys.exit(1)
    bdf, name, out = sys.argv[1:]
    props, glyphs = parse_bdf(Path(bdf))
    pixel_size = props.get("pixel_size", props.get("fbbx", (0, 0, 0, 0))[1] or 8)
    emit(name, props, glyphs, Path(out), pixel_size)


if __name__ == "__main__":
    main()
